### ISSUE TITLE
Error when import package

### ISSUE THREAD

**Issue by ali-memar** [psychomet/ng-antd-workspace#1]
hi,
I add your package to my angular project but when run, get an Error

Error detail:
```
user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
  NullInjectorError: No provider for CdkConnectedOverlay!
    at NullInjector.get (core.mjs:8096:27)
    at R3Injector.get (core.mjs:8546:33)
    at R3Injector.get (core.mjs:8546:33)
    at R3Injector.get (core.mjs:8546:33)
    at R3Injector.get (core.mjs:8546:33)
    at ChainedInjector.get (core.mjs:12915:36)
    at lookupTokenUsingModuleInjector (core.mjs:3505:39)
    at getOrCreateInjectable (core.mjs:3550:12)
    at Module.ɵɵdirectiveInject (core.mjs:10836:12)
    at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
```

**Comment by psychomet** [comment]
antd 14 need angular cdk 14,
update angular cdk to "@angular/cdk": "^14.2.2" or higher

**Comment by psychomet** [comment]
> hi, I add your package to my angular project but when run, get an Error
> 
> Error detail:
> 
> ```
> user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
>   NullInjectorError: No provider for CdkConnectedOverlay!
>     at NullInjector.get (core.mjs:8096:27)
>     at R3Injector.get (core.mjs:8546:33)
>     at R3Injector.get (core.mjs:8546:33)
>     at R3Injector.get (core.mjs:8546:33)
>     at R3Injector.get (core.mjs:8546:33)
>     at ChainedInjector.get (core.mjs:12915:36)
>     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
>     at getOrCreateInjectable (core.mjs:3550:12)
>     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
>     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> ```

antd 14 need angular cdk 14,
update angular cdk to "@angular/cdk": "^14.2.2" or higher

**Comment by ali-memar** [comment]
> > hi, I add your package to my angular project but when run, get an Error
> > Error detail:
> > ```
> > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> >   NullInjectorError: No provider for CdkConnectedOverlay!
> >     at NullInjector.get (core.mjs:8096:27)
> >     at R3Injector.get (core.mjs:8546:33)
> >     at R3Injector.get (core.mjs:8546:33)
> >     at R3Injector.get (core.mjs:8546:33)
> >     at R3Injector.get (core.mjs:8546:33)
> >     at ChainedInjector.get (core.mjs:12915:36)
> >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> >     at getOrCreateInjectable (core.mjs:3550:12)
> >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > ```
> 
> antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher

but my version of "@angular/cdk" is "^15.0.3"

**Comment by saeidi-dev** [comment]
I also have this error

  "@angular/cdk": "^14.2.3"

**Comment by psychomet** [comment]
> I also have this error
> 
> "@angular/cdk": "^14.2.3"

update to "@angular/cdk": "14.2.7"
I am working on a way to remove the need for AngularCDK and date-fns

**Comment by psychomet** [comment]
> > > hi, I add your package to my angular project but when run, get an Error
> > > Error detail:
> > > ```
> > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > >     at NullInjector.get (core.mjs:8096:27)
> > >     at R3Injector.get (core.mjs:8546:33)
> > >     at R3Injector.get (core.mjs:8546:33)
> > >     at R3Injector.get (core.mjs:8546:33)
> > >     at R3Injector.get (core.mjs:8546:33)
> > >     at ChainedInjector.get (core.mjs:12915:36)
> > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > >     at getOrCreateInjectable (core.mjs:3550:12)
> > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > ```
> > 
> > 
> > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> 
> but my version of "@angular/cdk" is "^15.0.3"

I released new version added   "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"]
to library please install latest version,
I work on commitizen for this library.
thanks

**Comment by ali-memar** [comment]
> 

this release has not working for me :(

> > > > hi, I add your package to my angular project but when run, get an Error
> > > > Error detail:
> > > > ```
> > > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > > >     at NullInjector.get (core.mjs:8096:27)
> > > >     at R3Injector.get (core.mjs:8546:33)
> > > >     at R3Injector.get (core.mjs:8546:33)
> > > >     at R3Injector.get (core.mjs:8546:33)
> > > >     at R3Injector.get (core.mjs:8546:33)
> > > >     at ChainedInjector.get (core.mjs:12915:36)
> > > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > > >     at getOrCreateInjectable (core.mjs:3550:12)
> > > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > > ```
> > > 
> > > 
> > > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> > 
> > 
> > but my version of "@angular/cdk" is "^15.0.3"
> 
> I released new version added "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"] to library please install latest version, I work on commitizen for this library. thanks

this release has not working for me and still the previous error has not been resolved :(

**Comment by psychomet** [comment]
> 

Please send me your package.json content of the file if you can.
It helps a lot to find the problem

**Comment by psychomet** [comment]
> > 
> 
> this release has not working for me :(
> 
> > > > > hi, I add your package to my angular project but when run, get an Error
> > > > > Error detail:
> > > > > ```
> > > > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > > > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > > > >     at NullInjector.get (core.mjs:8096:27)
> > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > >     at ChainedInjector.get (core.mjs:12915:36)
> > > > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > > > >     at getOrCreateInjectable (core.mjs:3550:12)
> > > > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > > > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > > > ```
> > > > 
> > > > 
> > > > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> > > 
> > > 
> > > but my version of "@angular/cdk" is "^15.0.3"
> > 
> > 
> > I released new version added "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"] to library please install latest version, I work on commitizen for this library. thanks
> 
> this release has not working for me and still the previous error has not been resolved :(

Please send me your package.json content of the file if you can.
It helps a lot to find the problem

**Comment by ali-memar** [comment]
> > > 
> > 
> > 
> > this release has not working for me :(
> > > > > > hi, I add your package to my angular project but when run, get an Error
> > > > > > Error detail:
> > > > > > ```
> > > > > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > > > > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > > > > >     at NullInjector.get (core.mjs:8096:27)
> > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > >     at ChainedInjector.get (core.mjs:12915:36)
> > > > > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > > > > >     at getOrCreateInjectable (core.mjs:3550:12)
> > > > > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > > > > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > > > > ```
> > > > > 
> > > > > 
> > > > > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> > > > 
> > > > 
> > > > but my version of "@angular/cdk" is "^15.0.3"
> > > 
> > > 
> > > I released new version added "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"] to library please install latest version, I work on commitizen for this library. thanks
> > 
> > 
> > this release has not working for me and still the previous error has not been resolved :(
> 
> Please send me your package.json content of the file if you can. It helps a lot to find the problem

my `package.json` content:
```
{
  "dependencies": {
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.3",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/forms": "^15.0.4",
    "@angular/localize": "^15.0.4",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@angular/service-worker": "^15.0.4",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "ag-grid-angular": "^28.2.1",
    "ag-grid-community": "^28.2.1",
    "ag-grid-enterprise": "^28.2.1",
    "ag-grid-odata": "^1.0.32",
    "bootstrap": "^5.2.3",
    "core-js": "^2.4.1",
    "jalali-moment": "^3.3.11",
    "lodash-es": "^4.17.21",
    "marked": "^4.0.19",
    "moment-jalaali": "^0.9.6",
    "ng-persian-datepicker": "^5.1.1",
    "ng-zorro-antd": "^14.3.0",
    "ngx-scrollbar": "^10.0.1",
    "ngx-toastr": "^15.2.0",
    "nz-date-picker-jalali": "^0.0.12",
    "rxjs": "^7.5.0",
    "tslib": "^2.4.0",
    "zone.js": "^0.11.6"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^15.0.0-beta.0",
    "@angular-devkit/build-angular": "^15.0.4",
    "@angular-eslint/builder": "^14.1.2",
    "@angular-eslint/eslint-plugin": "^14.1.2",
    "@angular-eslint/eslint-plugin-template": "^14.1.2",
    "@angular-eslint/schematics": "^14.1.2",
    "@angular-eslint/template-parser": "^14.1.2",
    "@angular/cli": "^15.0.4",
    "@angular/compiler-cli": "^15.0.4",
    "@angular/language-service": "^15.0.4",
    "@commitlint/cli": "^17.3.0",
    "@commitlint/config-angular": "^17.3.0",
    "@types/jasmine": "^3.10.6",
    "@types/jasminewd2": "^2.0.10",
    "@types/lodash-es": "^4.17.6",
    "@types/moment-jalaali": "^0.7.5",
    "@types/node": "^17.0.45",
    "@typescript-eslint/eslint-plugin": "^5.45.1",
    "@typescript-eslint/parser": "^5.45.1",
    "dotenv": "^16.0.3",
    "eslint": "^8.29.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "husky": "^8.0.2",
    "jasmine-core": "^4.4.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.0",
    "karma-chrome-launcher": "^3.1.1",
    "karma-cli": "^2.0.0",
    "karma-coverage": "^2.2.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "karma-junit-reporter": "^2.0.1",
    "karma-spec-reporter": "^0.0.34",
    "lint-staged": "^13.0.4",
    "pre-commit": "^1.2.2",
    "prettier": "^2.8.0",
    "prettier-eslint": "^15.0.1",
    "protractor": "~7.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.7.2"
  }
}
```

**Comment by psychomet** [comment]
> > > > 
> > > 
> > > 
> > > this release has not working for me :(
> > > > > > > hi, I add your package to my angular project but when run, get an Error
> > > > > > > Error detail:
> > > > > > > ```
> > > > > > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > > > > > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > > > > > >     at NullInjector.get (core.mjs:8096:27)
> > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > >     at ChainedInjector.get (core.mjs:12915:36)
> > > > > > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > > > > > >     at getOrCreateInjectable (core.mjs:3550:12)
> > > > > > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > > > > > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> > > > > 
> > > > > 
> > > > > but my version of "@angular/cdk" is "^15.0.3"
> > > > 
> > > > 
> > > > I released new version added "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"] to library please install latest version, I work on commitizen for this library. thanks
> > > 
> > > 
> > > this release has not working for me and still the previous error has not been resolved :(
> > 
> > 
> > Please send me your package.json content of the file if you can. It helps a lot to find the problem
> 
> my `package.json` content:
> 
> ```
> {
>   "dependencies": {
>     "@angular/animations": "^15.0.4",
>     "@angular/cdk": "^15.0.3",
>     "@angular/common": "^15.0.4",
>     "@angular/compiler": "^15.0.4",
>     "@angular/core": "^15.0.4",
>     "@angular/forms": "^15.0.4",
>     "@angular/localize": "^15.0.4",
>     "@angular/platform-browser": "^15.0.4",
>     "@angular/platform-browser-dynamic": "^15.0.4",
>     "@angular/router": "^15.0.4",
>     "@angular/service-worker": "^15.0.4",
>     "@ngx-translate/core": "^14.0.0",
>     "@ngx-translate/http-loader": "^7.0.0",
>     "ag-grid-angular": "^28.2.1",
>     "ag-grid-community": "^28.2.1",
>     "ag-grid-enterprise": "^28.2.1",
>     "ag-grid-odata": "^1.0.32",
>     "bootstrap": "^5.2.3",
>     "core-js": "^2.4.1",
>     "jalali-moment": "^3.3.11",
>     "lodash-es": "^4.17.21",
>     "marked": "^4.0.19",
>     "moment-jalaali": "^0.9.6",
>     "ng-persian-datepicker": "^5.1.1",
>     "ng-zorro-antd": "^14.3.0",
>     "ngx-scrollbar": "^10.0.1",
>     "ngx-toastr": "^15.2.0",
>     "nz-date-picker-jalali": "^0.0.12",
>     "rxjs": "^7.5.0",
>     "tslib": "^2.4.0",
>     "zone.js": "^0.11.6"
>   },
>   "devDependencies": {
>     "@angular-builders/custom-webpack": "^15.0.0-beta.0",
>     "@angular-devkit/build-angular": "^15.0.4",
>     "@angular-eslint/builder": "^14.1.2",
>     "@angular-eslint/eslint-plugin": "^14.1.2",
>     "@angular-eslint/eslint-plugin-template": "^14.1.2",
>     "@angular-eslint/schematics": "^14.1.2",
>     "@angular-eslint/template-parser": "^14.1.2",
>     "@angular/cli": "^15.0.4",
>     "@angular/compiler-cli": "^15.0.4",
>     "@angular/language-service": "^15.0.4",
>     "@commitlint/cli": "^17.3.0",
>     "@commitlint/config-angular": "^17.3.0",
>     "@types/jasmine": "^3.10.6",
>     "@types/jasminewd2": "^2.0.10",
>     "@types/lodash-es": "^4.17.6",
>     "@types/moment-jalaali": "^0.7.5",
>     "@types/node": "^17.0.45",
>     "@typescript-eslint/eslint-plugin": "^5.45.1",
>     "@typescript-eslint/parser": "^5.45.1",
>     "dotenv": "^16.0.3",
>     "eslint": "^8.29.0",
>     "eslint-config-prettier": "^8.5.0",
>     "eslint-plugin-prettier": "^4.2.1",
>     "husky": "^8.0.2",
>     "jasmine-core": "^4.4.0",
>     "jasmine-spec-reporter": "^7.0.0",
>     "karma": "^6.4.0",
>     "karma-chrome-launcher": "^3.1.1",
>     "karma-cli": "^2.0.0",
>     "karma-coverage": "^2.2.0",
>     "karma-coverage-istanbul-reporter": "~3.0.2",
>     "karma-jasmine": "^5.1.0",
>     "karma-jasmine-html-reporter": "^2.0.0",
>     "karma-junit-reporter": "^2.0.1",
>     "karma-spec-reporter": "^0.0.34",
>     "lint-staged": "^13.0.4",
>     "pre-commit": "^1.2.2",
>     "prettier": "^2.8.0",
>     "prettier-eslint": "^15.0.1",
>     "protractor": "~7.0.0",
>     "ts-node": "^10.9.1",
>     "typescript": "^4.7.2"
>   }
> }
> ```

I fixed this issue update nz-date-picker-jalali to antd 15 and angular cdk 15
please update nz-date-picker-jalali to lateset version.

demo: https://stackblitz.com/edit/angular-ivy-nqyckh?file=src/app/app.component.ts
thanks a lot <3

**Comment by ali-memar** [comment]
> 



> > > > > 
> > > > 
> > > > 
> > > > this release has not working for me :(
> > > > > > > > hi, I add your package to my angular project but when run, get an Error
> > > > > > > > Error detail:
> > > > > > > > ```
> > > > > > > > user.service.ts:82 ERROR NullInjectorError: R3InjectorError(DashboardModule)[CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay -> CdkConnectedOverlay]: 
> > > > > > > >   NullInjectorError: No provider for CdkConnectedOverlay!
> > > > > > > >     at NullInjector.get (core.mjs:8096:27)
> > > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > > >     at R3Injector.get (core.mjs:8546:33)
> > > > > > > >     at ChainedInjector.get (core.mjs:12915:36)
> > > > > > > >     at lookupTokenUsingModuleInjector (core.mjs:3505:39)
> > > > > > > >     at getOrCreateInjectable (core.mjs:3550:12)
> > > > > > > >     at Module.ɵɵdirectiveInject (core.mjs:10836:12)
> > > > > > > >     at NodeInjectorFactory.NzConnectedOverlayDirective_Factory [as factory] (ng-zorro-antd-core-overlay.mjs:139:114)
> > > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > antd 14 need angular cdk 14, update angular cdk to "@angular/cdk": "^14.2.2" or higher
> > > > > > 
> > > > > > 
> > > > > > but my version of "@angular/cdk" is "^15.0.3"
> > > > > 
> > > > > 
> > > > > I released new version added "allowedNonPeerDependencies": ["tslib", "angular", "date-fns", "@ant-design/icons-angular"] to library please install latest version, I work on commitizen for this library. thanks
> > > > 
> > > > 
> > > > this release has not working for me and still the previous error has not been resolved :(
> > > 
> > > 
> > > Please send me your package.json content of the file if you can. It helps a lot to find the problem
> > 
> > 
> > my `package.json` content:
> > ```
> > {
> >   "dependencies": {
> >     "@angular/animations": "^15.0.4",
> >     "@angular/cdk": "^15.0.3",
> >     "@angular/common": "^15.0.4",
> >     "@angular/compiler": "^15.0.4",
> >     "@angular/core": "^15.0.4",
> >     "@angular/forms": "^15.0.4",
> >     "@angular/localize": "^15.0.4",
> >     "@angular/platform-browser": "^15.0.4",
> >     "@angular/platform-browser-dynamic": "^15.0.4",
> >     "@angular/router": "^15.0.4",
> >     "@angular/service-worker": "^15.0.4",
> >     "@ngx-translate/core": "^14.0.0",
> >     "@ngx-translate/http-loader": "^7.0.0",
> >     "ag-grid-angular": "^28.2.1",
> >     "ag-grid-community": "^28.2.1",
> >     "ag-grid-enterprise": "^28.2.1",
> >     "ag-grid-odata": "^1.0.32",
> >     "bootstrap": "^5.2.3",
> >     "core-js": "^2.4.1",
> >     "jalali-moment": "^3.3.11",
> >     "lodash-es": "^4.17.21",
> >     "marked": "^4.0.19",
> >     "moment-jalaali": "^0.9.6",
> >     "ng-persian-datepicker": "^5.1.1",
> >     "ng-zorro-antd": "^14.3.0",
> >     "ngx-scrollbar": "^10.0.1",
> >     "ngx-toastr": "^15.2.0",
> >     "nz-date-picker-jalali": "^0.0.12",
> >     "rxjs": "^7.5.0",
> >     "tslib": "^2.4.0",
> >     "zone.js": "^0.11.6"
> >   },
> >   "devDependencies": {
> >     "@angular-builders/custom-webpack": "^15.0.0-beta.0",
> >     "@angular-devkit/build-angular": "^15.0.4",
> >     "@angular-eslint/builder": "^14.1.2",
> >     "@angular-eslint/eslint-plugin": "^14.1.2",
> >     "@angular-eslint/eslint-plugin-template": "^14.1.2",
> >     "@angular-eslint/schematics": "^14.1.2",
> >     "@angular-eslint/template-parser": "^14.1.2",
> >     "@angular/cli": "^15.0.4",
> >     "@angular/compiler-cli": "^15.0.4",
> >     "@angular/language-service": "^15.0.4",
> >     "@commitlint/cli": "^17.3.0",
> >     "@commitlint/config-angular": "^17.3.0",
> >     "@types/jasmine": "^3.10.6",
> >     "@types/jasminewd2": "^2.0.10",
> >     "@types/lodash-es": "^4.17.6",
> >     "@types/moment-jalaali": "^0.7.5",
> >     "@types/node": "^17.0.45",
> >     "@typescript-eslint/eslint-plugin": "^5.45.1",
> >     "@typescript-eslint/parser": "^5.45.1",
> >     "dotenv": "^16.0.3",
> >     "eslint": "^8.29.0",
> >     "eslint-config-prettier": "^8.5.0",
> >     "eslint-plugin-prettier": "^4.2.1",
> >     "husky": "^8.0.2",
> >     "jasmine-core": "^4.4.0",
> >     "jasmine-spec-reporter": "^7.0.0",
> >     "karma": "^6.4.0",
> >     "karma-chrome-launcher": "^3.1.1",
> >     "karma-cli": "^2.0.0",
> >     "karma-coverage": "^2.2.0",
> >     "karma-coverage-istanbul-reporter": "~3.0.2",
> >     "karma-jasmine": "^5.1.0",
> >     "karma-jasmine-html-reporter": "^2.0.0",
> >     "karma-junit-reporter": "^2.0.1",
> >     "karma-spec-reporter": "^0.0.34",
> >     "lint-staged": "^13.0.4",
> >     "pre-commit": "^1.2.2",
> >     "prettier": "^2.8.0",
> >     "prettier-eslint": "^15.0.1",
> >     "protractor": "~7.0.0",
> >     "ts-node": "^10.9.1",
> >     "typescript": "^4.7.2"
> >   }
> > }
> > ```
> 
> I fixed this issue update nz-date-picker-jalali to antd 15 and angular cdk 15 please update nz-date-picker-jalali to lateset version.
> 
> demo: https://stackblitz.com/edit/angular-ivy-nqyckh?file=src/app/app.component.ts thanks a lot <3

yes, this worked. thank you so much ❤

**Comment by ali-memar** [comment]
When the date is in the form of a string, datepicker Gregorian date is selected but we want the date converted to Jalali

it worked:
`date = new Date();` OR `date = new Date("2022-07-14T00:00:00");`
`<nz-date-picker [(ngModel)]="date"></nz-date-picker>`

it not worked:
`date = "2022-07-14T00:00:00";`
`<nz-date-picker [(ngModel)]="date"></nz-date-picker>`

To solve this problem, it is better to check if the input is a string and convert it to a date
`date = !(data instanceof Date) ? date = new Date(date) : date; `

**Comment by psychomet** [comment]
> When the date is in the form of a string, datepicker Gregorian date is selected but we want the date converted to Jalali
> 
> it worked: `date = new Date();` OR `date = new Date("2022-07-14T00:00:00");` `<nz-date-picker [(ngModel)]="date"></nz-date-picker>`
> 
> it not worked: `date = "2022-07-14T00:00:00";` `<nz-date-picker [(ngModel)]="date"></nz-date-picker>`
> 
> To solve this problem, it is better to check if the input is a string and convert it to a date `date = !(data instanceof Date) ? date = new Date(date) : date; `

I will definitely work. You can also merge request on repository bro.
